datasources:
  default:
    connection:
      url: ${MONGO_URL}
    objectFiles:
      - "./src/**"
    appFiles:
      - "./src/**"
public:
  webservices:
    www:
      status: active
      url: 'https://www.steedos.com/'
    creator:
      status: active
      url: ${STEEDOS_CREATOR_URL}
    workflow:
      status: active
      url: ${STEEDOS_WORKFLOW_URL}
  cfs:
    store: ${STEEDOS_CFS_STORE}
    local:
      folder: ${STEEDOS_STORAGE_DIR}
  admin:
    disableAddSpace: false
  accounts:
    disableAccountRegistration: false
    UTF8_Names_Validation: '[A-Za-z0-9-_.\u00C0-\u017F\u4e00-\u9fa5]+'
    loginExpirationInDays: 1825
  phone:
    forceAccountBindPhone: false
  cloudAdminSpaceId: cloud_admin
  templateSpaceId: 5e38d51b41386900110ff5c5
  is_group_company: true
  workflow:
    hideLastSignApproveDescription: true
    instance_allow_distribute: true
cfs:
  aliyun:
    region: ${STEEDOS_CFS_ALIYUN_REGION}
    bucket: ${STEEDOS_CFS_ALIYUN_BUCKET}
    accessKeyId: ${STEEDOS_CFS_ALIYUN_ACCESSKEYID}
    secretAccessKey: ${STEEDOS_CFS_ALIYUN_SECRETACCESSKEY}
  worker:
    enabled: true
cron:
  # statistics: 0 0 0 * * *
  # mailqueue_interval: 1000
  # push_interval: 1000
  # calendar_dav_interval: 30000
  # calendar_remind: 60000
  # webhookqueue_interval: 1000
  instancerecordqueue_interval: 10000
push:
  apn:
    keyData: ${STEEDOS_PUSH_APN_DATA}
    certData: ${STEEDOS_PUSH_APN_DATA}
  gcm:
    apiKey: xxx
  xinge:
    accessId: ${STEEDOS_PUSH_XINGE_ACCESSID}
    secretKey: ${STEEDOS_PUSH_XINGE_SECRETKEY}
  huawei:
    appId: ${STEEDOS_PUSH_HUAWEI_APPID}
    appSecret: ${STEEDOS_PUSH_HUAWEI_APPSECRET}
    appPkgName: ${STEEDOS_PUSH_HUAWEI_APPPKGNAME}
  mi:
    appSecret: ${STEEDOS_PUSH_MI_APPSECRET}
    production: ${STEEDOS_PUSH_MI_PRODUCTION}
email:
  from: 华炎魔方 <noreply@steedos.com>
  url: xxx
logger:
  enabled: true
  showPackage: true
  showFileAndLine: true
  logLevel: 0
  viewLimit: 1000
billing:
  appid: ${STEEDOS_BILLING_APPID}
  mch_id: ${STEEDOS_BILLING_MCH_ID}
  partner_key: ${STEEDOS_BILLING_PARTNER_KEY}
plugins:
  - "@steedos/accounts"
tenant:
  saas: false
  name: 华炎云
  enable_register: true
  enable_forget_password: true
  enable_create_tenant: true
  enable_password_login: true
  enable_bind_email: false
  enable_bind_mobile: false
accounts:
  mobile_phone_locales: ['zh-CN']