datasources:
  default:
    connection:
      url: ${MONGO_URL}
    objectFiles:
      - "./src/**"
public:
  cfs:
    store: ${STEEDOS_CFS_STORE}
    local:
      folder: ${STEEDOS_STORAGE_DIR}
email:
  host:
  port: 465
  username:
  password:
  secure: true
  from:
tenant:
  _id:
  name: 华炎魔方
  logo_url:
  background_url:
  enable_register: true
  enable_forget_password: false
  enable_create_tenant: true
  enable_password_login: true
  enable_bind_email: false
  enable_bind_mobile: false
plugins:
  - "@steedos/accounts"
  - "@steedos/app-crm"
  - "@steedos/app-contracts"
  - "@steedos/plugin-qywx"
  - "@steedos/plugin-enterprise"
cron:
  instancerecordqueue_interval: 10000
